apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  targetNamespace: loki-system
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      version: 2.10.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClassName: gp3
        size: 10Gi
    promtail:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    filebeat:
      enabled: false
    logstash:
      enabled: false
    fluent-bit:
      enabled: false
    fluentd:
      enabled: false
