apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  targetNamespace: alloy-system
  interval: 10m
  chart:
    spec:
      chart: alloy
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    alloy:
      configMap:
        content: |
          logging {
            level = "info"
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.kubernetes "nodes" {
            role = "node"
          }

          discovery.kubernetes "services" {
            role = "service"
          }

          discovery.kubernetes "endpoints" {
            role = "endpoints"
          }

          discovery.kubernetes "endpointslices" {
            role = "endpointslice"
          }

          discovery.kubernetes "ingresses" {
            role = "ingress"
          }

          // Scrape logs from Kubernetes pods
          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets
            rule {
              source_labels = ["__meta_kubernetes_pod_phase"]
              regex = "Pending|Succeeded|Failed|Unknown"
              action = "drop"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_annotation_kubectl_kubernetes_io_default_container"]
              target_label = "__service__"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              target_label = "__service__"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              target_label = "__service__"
            }
            rule {
              source_labels = ["__service__"]
              regex = ""
              target_label = "__service__"
              replacement = "unknown-service"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label = "__tmp_container_name"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label = "__host__"
            }
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              target_label = "__path__"
              separator = "/"
              replacement = "/var/log/pods/*$1/*.log"
            }
          }

          loki.source.kubernetes "pod_logs" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.process.pod_logs.receiver]
          }

          loki.process "pod_logs" {
            forward_to = [loki.write.default.receiver]

            stage.cri {}

            stage.labels {
              values = {
                namespace = "",
                pod       = "",
                container = "",
              }
            }
          }

          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.loki-system.svc.cluster.local/loki/api/v1/push"
            }
          }
    controller:
      type: daemonset
      tolerations:
        - operator: Exists
