apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: "1.28.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  dependsOn:
    - name: istio-base
  values:
    telemetry:
      v2:
        enabled: true
    pilot:
      env:
        EXTERNAL_ISTIOD: false
      tolerations:
        - key: "node-type"
          operator: "Equal"
          value: "system"
          effect: "NoSchedule"
