apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: common-gateway
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.local"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*.local"
    tls:
      mode: SIMPLE
      credentialName: local-tls-secret
