apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: flux-system
spec:
  targetNamespace: opentelemetry-system
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.102.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-contrib
