apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: "1.28.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  values:
    defaultRevision: default
