apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: "2.54.1"
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
      interval: 12h
  targetNamespace: kube-system
  values:
    controller:
      serviceAccount:
        create: true
        name: ebs-csi-controller-sa
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::054715966742:role/fluxcd-dev-ebs-csi-driver-role"
