apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-base
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux-config/infrastructure
  prune: true
  wait: true
